export enum Page {
    COLLECT = '/collect',
    ACCOUNT = '/account',
    COLLECTION = '/collection',
    CLUE = '/clue',
    DASHBOARD = '/dashboard',
    RANKING = '/ranking',
    FAQ = '/faq',
    RULEBOOK = '/rulebook',
    GUILD = '/guild',
    MAP = '/map',
    ACHIEVEMENTS = '/achievements',
    MAIN = '/',
    LOGIN = '/auth/login',
    LOGIN_EMAIL = '/auth/login-email',
    REGISTER = '/auth/register',
    REGISTER_EMAIL = '/auth/register-email',
    ACCOUNT_SETUP = '/auth/account-setup',
    ADMIN_PINS = '/admin/pins',
    ADMIN_RECENTLY_COLLECTED = '/admin/recently-collected',
    ADMIN_USERS = '/admin/users',
    ADMIN_USER = '/admin/user',
    ADMIN_ACHIEVEMENTS = '/admin/achievements',
    ADMIN_PHOTO_REVIEW = '/admin/photo-review',
    ADMIN_FEEDBACK = '/admin/feedback',
}
